"""Project the pinned archival review into browser-safe delivery metadata.

No source prose is promoted to a personal claim. --check verifies committed
projection bytes; source/DOCX integrity is checked by the original frozen audit.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REVIEW = ROOT / 'docs/knowledge-model/data/basic_sentence_review.json'
TARGET = ROOT / 'dosa-app/engine/src/basicSentenceData.js'

def render():
    value = json.loads(REVIEW.read_text(encoding='utf-8'))
    canonical = json.dumps(value, ensure_ascii=True, sort_keys=True, allow_nan=False)
    if hashlib.sha256(canonical.encode()).hexdigest() != '6c5ce9d82a8f589cd30f8c85548e9ce42fdbee1ccf405e26d54ca3d31199d754':
        raise ValueError('Unreviewed source-policy change')
    spans = {s['id']: s for s in value['spans']}
    items = []
    for item in value['items']:
        records = []
        for span_id in item['evidence']:
            span = spans[span_id]
            unit = value['source_units'][span['unit']]
            records.append(dict(unit=span['unit'], doc=span['unit'].rsplit('#', 1)[0],
                title=unit['title'], archive=unit['archive_path'], lineage=unit['lineage'],
                bodyParagraphs=span['body_paragraphs'],
                xmlParagraphs=[p['xml_paragraph'] for p in span['paragraphs']]))
        items.append(dict(id=item['id'], key=item['key'], pointer=item['pointer'],
            needles=[item['draft_value']] if isinstance(item['draft_value'],str) else [v['내용'] for v in item['draft_value']['견해']],
            review=item['review'], sources=records, personalApplication='withheld',
            trainingEligible=False, probability=None))
    return '// Generated by scripts/build_basic_sentence_policy.py. Original review and KB remain unchanged.\nexport default ' + json.dumps(items,ensure_ascii=False,indent=2) + ';\n'

if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    expected=render()
    if args.check:
        if TARGET.read_text(encoding='utf-8') != expected: raise ValueError('Basic sentence projection drift')
        print('14 review records: projection verified; no personal inference approval')
    else: TARGET.write_text(expected,encoding='utf-8')
