// Generated by scripts/build_gapin_sentence_policy.py; archival review remains unchanged.
export default [
  {
    "id": "GI01",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "핵심"
    ],
    "needles": [
      "하늘과 땅이 모두 갑목인 간여지동 일주. 자존심과 자아가 강하고 매사에 적극적·능동적이며, 십이운성 건록의 막강한 힘으로 남의 도움 없이 혼자 일구어내는 힘이 강하다. 지장간이 비견-식신-편재로 흘러 기본적인 재물복이 있으나, 강한 힘을 어떻게 조절해 쓰느냐에 따라 삶의 향방이 크게 갈린다."
    ],
    "review": {
      "status": "mixed_sources_and_time_context_lost",
      "conditions": "앞부분은 일주론 기본성향·건록, 흐름은 같은 글11문단, 재물복은 고급1의 일지 지장간 식상/재성 주장이다. 마지막 삶의 향방 문장은 경자년 단락34문단에서 재사용했다.",
      "exceptions_or_counterpoints": "강한 자아의 마찰/배우자 문제라는 인접 단점을 함께 보존. 저자별 재물복과 흐름을 하나의 검증된 법칙으로 합치지 않는다.",
      "scope": "여러 문단과 두 출처를 합친 핵심 요약. 단일 출처/단일 시기의 일반규칙으로 승인하지 않는다.",
      "unknown": "재물복·힘 조절·삶의 향방의 관측 정의와 개인 효과가 없다.",
      "time_scope": "마지막 문장은 경자년(2020년) 운세 제목 아래34문단. 출생연도와 무관한 영구 규칙으로 승격하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "고급1 계보는 원문 저자 미확정. 일주론/현묘 글은 yavares.tistory.com 같은 계보. 글 수나 재사용을 독립 지지수로 세지 않음."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          4,
          7
        ],
        "xmlParagraphs": [
          252,
          253,
          254,
          255
        ]
      },
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          11,
          12
        ],
        "xmlParagraphs": [
          259,
          260
        ]
      },
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          15,
          17
        ],
        "xmlParagraphs": [
          474,
          475,
          476
        ]
      },
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          33,
          40
        ],
        "xmlParagraphs": [
          281,
          282,
          283,
          284,
          285,
          286,
          287,
          288
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN01",
      "IN05"
    ],
    "reuseKind": "semantic_partial_reuse",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI02",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "성격",
      0
    ],
    "needles": [
      "밝고 명랑한 기운이 넘치고 매사에 적극적·능동적 — 자존심과 자아의 끝판왕 (천간·지지 모두 갑목)"
    ],
    "review": {
      "status": "source_attribution_mismatch",
      "conditions": "저자의 갑인일주 일반 성향 주장. 천간·지지 모두 갑목은 본기의 표현이며 인목 전체가 갑목 하나라는 뜻으로 확대하지 않음.",
      "exceptions_or_counterpoints": "강점 다음 문단의 자기중심성·마찰 설명과 별도로 보존.",
      "scope": "원국 일주 유형; 개인에게 적용되지 않은 문헌 요약. 앱 대표 첫 출처는 고급1#0018이나 이 표현은 일주론#0002에서 확인.",
      "unknown": "다른 기둥·강도·환경·개인 성향은 검증하지 않음.",
      "time_scope": "기존 검토의 원국/일주 유형·문맥 범위 보존. 실제 시점 조건은 평가하지 않음.",
      "gender_scope": "기존 검토의 성별 범위 유지. 명시 없는 성별을 추가하지 않음.",
      "position_scope": "기존 검토의 일간/일지·다른 기둥/월주·운 조건을 그대로 보존하고 실제 명식 조건은 평가하지 않음.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          4,
          7
        ],
        "xmlParagraphs": [
          252,
          253,
          254,
          255
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN01"
    ],
    "reuseKind": "exact_prior_pointer",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI03",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "성격",
      1
    ],
    "needles": [
      "우두머리 기질로 간섭·통제를 꺼리고 모든 것을 자신이 주도하려 함 (일지 비견 — 고집·자존심이 강하고 자기중심적 생활태도)"
    ],
    "review": {
      "status": "scope_compressed",
      "conditions": "우두머리·간섭 회피는 갑목일간 일반, 주도성·고집·자기중심성은 일지 비견 설명이다.",
      "exceptions_or_counterpoints": "같은 문맥에 융통성 부족과 배우자가 동료 또는 경쟁자가 되는 양면이 있다.",
      "scope": "갑인 고유성 하나로 압축하지 않고 갑목일간과 일지 비견의 두 범위를 구별한다.",
      "unknown": "개인 자존심/주도성의 강도나 행동 관찰은 검증하지 않음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "unresolved:명리학탐구(고급1). 보관 문서명만으로 저자·원저 계보를 확정하지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          7,
          14
        ],
        "xmlParagraphs": [
          466,
          467,
          468,
          469,
          470,
          471,
          472,
          473
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI04",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "성격",
      2
    ],
    "needles": [
      "남의 도움 없이 자기 혼자 힘으로 일구어내는 힘이 강함 (십이운성 건록의 막강한 힘)"
    ],
    "review": {
      "status": "source_supported_uncomputed",
      "conditions": "일주론6문단은 건록의 힘과 혼자 일구는 힘을 장점으로 설명한다.",
      "exceptions_or_counterpoints": "같은 문단의 자기중심성 및7문단 마찰/배우자 설명을 별도로 보존한다.",
      "scope": "같은 출처·같은 원문을 IN01과 나눠 재사용한 항목이다. 새 독립 지지가 아니다.",
      "unknown": "건록 존재와 개인의 독립 성취를 연결하는 관측 자료는 없음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          4,
          7
        ],
        "xmlParagraphs": [
          252,
          253,
          254,
          255
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN01"
    ],
    "reuseKind": "shared_evidence_only",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI05",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "성격",
      3
    ],
    "needles": [
      "손해볼 것을 알아도 바른 말을 해야 직성이 풀림 — 이슈와 인기를 몰고 다니나 실속은 부족 (목 과다 = 용기 과잉, '간뎅이가 부은' 형국)"
    ],
    "review": {
      "status": "condition_omitted",
      "conditions": "67문단은 연주·월주·시주 등 다른 요인에 의해 얼마든지 달라질 수 있다고 명시. 68문단의 목 과다를 별도 조건으로 보존.",
      "exceptions_or_counterpoints": "일반적인 목의 유연성과 과도한 목의 경직성을 저자가 대비함.",
      "scope": "같은 yavares 저자의 추가 글 /388. 일주론 /59와 독립 저자 지지로 세지 않음.",
      "unknown": "목 과다의 계산 기준·개인 발현은 미확정. 신체 손상·간 건강 비유를 진단으로 쓰지 않음.",
      "time_scope": "기존 검토의 원국/일주 유형·문맥 범위 보존. 실제 시점 조건은 평가하지 않음.",
      "gender_scope": "기존 검토의 성별 범위 유지. 명시 없는 성별을 추가하지 않음.",
      "position_scope": "기존 검토의 일간/일지·다른 기둥/월주·운 조건을 그대로 보존하고 실제 명식 조건은 평가하지 않음.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "현묘의 사주 이야기 글모음#0032",
        "doc": "현묘의 사주 이야기 글모음",
        "title": "간뎅이가 부은 사주 (feat. 갑인일주)",
        "archive": "정제본/현묘의 사주 이야기 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          65,
          72
        ],
        "xmlParagraphs": [
          2469,
          2470,
          2471,
          2472,
          2473,
          2474,
          2475,
          2476
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN02"
    ],
    "reuseKind": "exact_prior_pointer",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI06",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "성격",
      4
    ],
    "needles": [
      "나무 특유의 탐구심·호기심·인문적 기운이 강하고 머리회전이 빨라 이벤트·기획에 능함"
    ],
    "review": {
      "status": "modality_compressed",
      "conditions": "비견-식신-편재 흐름 설명 뒤 목의 탐구심/호기심/인문 기운과 기획 능력을 서술한다.",
      "exceptions_or_counterpoints": "원문은 이벤트·기획에 능한 경우가 많다고 표현하며 모든 개인의 능력을 단정하지 않는다.",
      "scope": "저자 유형 설명. 지장간의 흐름과 인지능력 효과를 같은 검증 수준으로 취급하지 않는다.",
      "unknown": "기획/인지능력 정의·표본·빈도·대조군 없음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          11,
          12
        ],
        "xmlParagraphs": [
          259,
          260
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI07",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "성격",
      5
    ],
    "needles": [
      "완고하고 고집이 강해 주변과 화합하기 힘들고 적이 많음 — 유연성·융통성 부족"
    ],
    "review": {
      "status": "scope_and_modality_compressed",
      "conditions": "완고함/유연성 부족은 고급1 갑목일간 일반, 적이 많다는 표현은 일주론 갑인 성향 절이다.",
      "exceptions_or_counterpoints": "각각 경향/쉽다/많은 사람이란 범위와 원문의 강점도 보존한다.",
      "scope": "서로 다른 일반범위와 표현 강도를 합친 문장. 두 출처를 독립 개인 검증으로 세지 않는다.",
      "unknown": "타인 갈등과 적의 범위·실제 개인 행동은 미검증.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "고급1 계보는 원문 저자 미확정. 일주론/현묘 글은 yavares.tistory.com 같은 계보. 글 수나 재사용을 독립 지지수로 세지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          7,
          10
        ],
        "xmlParagraphs": [
          466,
          467,
          468,
          469
        ]
      },
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          4,
          7
        ],
        "xmlParagraphs": [
          252,
          253,
          254,
          255
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI08",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "성격",
      6
    ],
    "needles": [
      "시작의 힘이 강한 만큼 마무리와 실속 챙기기는 약함"
    ],
    "review": {
      "status": "scope_and_condition_omitted",
      "conditions": "시작/마무리는 고급1의 갑목일간 설명과 현묘75문단에 있다. 현묘67문단은 연·월·시 등 다른 요인에 따라 얼마든지 달라진다고 명시한다.",
      "exceptions_or_counterpoints": "현묘73~86은 갑인의 용기와 주변인의 잇속을 대비하는 수사적 문맥이다.",
      "scope": "갑목일간 일반과 갑인 사례 수사를 구분. 실속을 챙기기 약함은 IN02의 실속 부족과 의미가 겹치는 하위절이며 시작/마무리는 별도 근거다. 전체 문구 중복이나 실행 조건으로 바꾸지 않는다.",
      "unknown": "시작·마무리·실속의 측정 기준 및 다른 기둥 영향은 미확정.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "고급1 계보는 원문 저자 미확정. 일주론/현묘 글은 yavares.tistory.com 같은 계보. 글 수나 재사용을 독립 지지수로 세지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          7,
          10
        ],
        "xmlParagraphs": [
          466,
          467,
          468,
          469
        ]
      },
      {
        "unit": "현묘의 사주 이야기 글모음#0032",
        "doc": "현묘의 사주 이야기 글모음",
        "title": "간뎅이가 부은 사주 (feat. 갑인일주)",
        "archive": "정제본/현묘의 사주 이야기 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          65,
          86
        ],
        "xmlParagraphs": [
          2469,
          2470,
          2471,
          2472,
          2473,
          2474,
          2475,
          2476,
          2477,
          2478,
          2479,
          2480,
          2481,
          2482,
          2483,
          2484,
          2485,
          2486,
          2487,
          2488,
          2489,
          2490
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN02"
    ],
    "reuseKind": "semantic_partial_reuse",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI09",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "직업",
      0
    ],
    "needles": [
      "남자는 경쟁하여 쟁취하는 사업길 적성 — 직장생활 중에도 자기 사업을 일으키는 성향 (식상이 있으면 전문분야 사업, 없으면 자영업, 관성 金이 튼튼하면 직장에서 크게 성공)"
    ],
    "review": {
      "status": "conditions_preserved_uncomputed",
      "conditions": "남자, 식상 있음/없음, 관성 금이 튼튼함을 각각 구별한다.",
      "exceptions_or_counterpoints": "관성 금이 튼튼하면 직장 성공이라는 같은 문단의 대안을 보존. 사업만 적성이라고 단정하지 않음.",
      "scope": "저자의 성별·직업 관련 주장. 원국 조건 검사는 하지 않음.",
      "unknown": "식상의 존재/강도·관성 튼튼함의 정량 기준 및 직업 성과 자료 없음.",
      "time_scope": "기존 검토의 원국/일주 유형·문맥 범위 보존. 실제 시점 조건은 평가하지 않음.",
      "gender_scope": "남자·식상·관성의 원문 갈래를 보존.",
      "position_scope": "기존 검토의 일간/일지·다른 기둥/월주·운 조건을 그대로 보존하고 실제 명식 조건은 평가하지 않음.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          9,
          12
        ],
        "xmlParagraphs": [
          257,
          258,
          259,
          260
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN03"
    ],
    "reuseKind": "exact_prior_pointer",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI10",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "직업",
      1
    ],
    "needles": [
      "여자는 식상이 있으면 교육·학원·요식업, 없으면 자영업·부동산 적성"
    ],
    "review": {
      "status": "conditions_preserved_uncomputed",
      "conditions": "여자와 식상 있음/없음의 분기를 보존. 식상 있음은 교육/학원/요식업, 없으면 자영업/부동산이라는 저자 주장이다.",
      "exceptions_or_counterpoints": "앞 남자 절의 금 관성 직장 성공을 여성 규칙으로 무단 전이하지 않는다.",
      "scope": "성별과 직업을 연결한 문헌의 조건부 주장으로만 기록한다.",
      "unknown": "식상 표면/지장간 범위·강도·적성/직업 성과 자료 없음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "여자 조건이 원문에 명시됨. 성별만으로 직업 적성을 정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          9,
          12
        ],
        "xmlParagraphs": [
          257,
          258,
          259,
          260
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN03"
    ],
    "reuseKind": "shared_evidence_only",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI11",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "직업",
      2
    ],
    "needles": [
      "비견-식신-편재로 자연스럽게 흐르는 힘 — 사업도 좋지만 학문·기술·예술 분야에서 강한 힘을 발휘하며, 위대한 인문학자 중에 갑인일주가 많음"
    ],
    "review": {
      "status": "empirical_claim_without_data",
      "conditions": "비견-식신-편재 흐름, 학문/기술/예술 분야, 위대한 인문학자 중 갑인이 많다는 서술이11~12문단에 있다.",
      "exceptions_or_counterpoints": "사업에도 괜찮다는 대안이 있으며 특정 분야만 적합하다는 뜻으로 좁히지 않는다.",
      "scope": "저자 서술을 찾았다는 검수. 인문학자 빈도에 대한 통계 검증이 아니다.",
      "unknown": "대상 명단·생시 신뢰성·표본 분모·비교집단이 제공되지 않음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          11,
          12
        ],
        "xmlParagraphs": [
          259,
          260
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI12",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "직업",
      3
    ],
    "needles": [
      "간여지동이라 몸을 써서 기운을 발산·실현해야 함 — 머리로 생각하지 말고 몸으로 생각할 것"
    ],
    "review": {
      "status": "advice_not_occupation_rule",
      "conditions": "간여지동의 기운을 몸으로 발산하라는16문단 조언이다.",
      "exceptions_or_counterpoints": "13~17문단의 고립/자존심 억압 문맥을 보존하며 특정 직업 분류는 원문에 없다.",
      "scope": "몸을 쓰라는 조언을 직업 적성이나 인지 능력의 평가로 바꾸지 않는다.",
      "unknown": "활동량/생활환경/건강 상태·조언 효과 미검증.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          13,
          18
        ],
        "xmlParagraphs": [
          261,
          262,
          263,
          264,
          265,
          266
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI13",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "관계",
      0
    ],
    "needles": [
      "남녀 모두 일지에 건록(비견)이 있어 부부궁이 위태로움 — 올곧은 성질과 자기 의견 고집으로 배우자와 트러블이 많음"
    ],
    "review": {
      "status": "conditional_claim_uncomputed",
      "conditions": "20문단은 남녀 공통의 건록과 자기 의견 고집을 배우자 갈등에 연결한다.",
      "exceptions_or_counterpoints": "24문단은 배우자를 애인처럼 대하는 반대 방향,25문단은 특정 사건에서 관계가 가까워질 수 있다는 예외 서술을 포함한다.",
      "scope": "문헌의 결혼관계 주장과 실제 부부관계 판단은 분리한다.",
      "unknown": "관계 갈등의 관측 정의/환경/당사자 행동 자료가 없다.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "남녀 모두라는 원문 범위.21~27의 성별 분기와 혼합하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          19,
          27
        ],
        "xmlParagraphs": [
          267,
          268,
          269,
          270,
          271,
          272,
          273,
          274,
          275
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI14",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "관계",
      1
    ],
    "needles": [
      "배우자도 비견의 성향이라 한마음으로 일을 추진하기도 하지만 때로는 심한 경쟁자가 됨 (간여지동 일주는 배우자궁이 다소 불리)"
    ],
    "review": {
      "status": "alternatives_preserved_uncomputed",
      "conditions": "일지 비견/배우자궁 설명에서 배우자가 같은 일을 추진하거나 심한 경쟁자가 될 수 있다고 한다.",
      "exceptions_or_counterpoints": "같은 방향 협력과 경쟁 두 갈래가 함께 있다. 항상 불리하다는 확정은 금지한다.",
      "scope": "간여지동 유형에 관한 저자 해석. 실제 배우자 명식/성격을 확정하지 않는다.",
      "unknown": "동료/경쟁의 전환 조건과 개인 부부관계는 미검증.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "unresolved:명리학탐구(고급1). 보관 문서명만으로 저자·원저 계보를 확정하지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          11,
          14
        ],
        "xmlParagraphs": [
          470,
          471,
          472,
          473
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI15",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "관계",
      2
    ],
    "needles": [
      "여자는 남편을 다툴 비견이 지지에 있어 남편궁이 좋지 않음 — 결혼이 늦어지고, 원국에 水 인성과 金 관성이 없으면 행복한 결혼생활이 어렵다고 봄; 여자가 남자를 먹여 살리는 경우가 많음"
    ],
    "review": {
      "status": "separated_paragraphs_and_conditions",
      "conditions": "21문단은 여자·지지 비견 및 원국 인성 水/관성 金 부재를 말한다.26문단의 부양 주장은25문단의 관계 반전과27문단의 의탁 대조 사이에 있다.",
      "exceptions_or_counterpoints": "24문단의 태도 변화,25문단의 특정 관계 반전,27문단의 반대 생활방식을 함께 남긴다. 두 문단을 하나의 결혼 실패 인과식으로 합치지 않는다.",
      "scope": "성별/결혼/부양에 관한 저자의 통계적 표현을 문헌 주장으로만 보존한다.",
      "unknown": "水와金 부재의 구체적 판정 범위·결혼 통계/분모/관측값 없음. 부재의 AND/OR를 임의 실행식으로 확정하지 않음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "여자에 대한 원문 주장. 개인 성별만으로 결혼·부양·성향을 추정하지 않음.",
      "position_scope": "원국 水 인성·金 관성의 부재와 지지 비견을 언급하나 표면/지장간·자리 범위는 명시되지 않음.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          19,
          27
        ],
        "xmlParagraphs": [
          267,
          268,
          269,
          270,
          271,
          272,
          273,
          274,
          275
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI16",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "관계",
      3
    ],
    "needles": [
      "남자는 사주에 비겁이 있으면 결혼이 많이 늦어지고, 일찍 결혼하면 우여곡절이 많음 (병화가 천간에 뜨면 부부궁이 좋아지고, 사화나 진토를 만나면 더 어려움)"
    ],
    "review": {
      "status": "anaphora_and_position_scope_unresolved",
      "conditions": "22문단은 남자·사주 비겁·이른 결혼/늦은 결혼,23문단은 이 경우 병화가 하늘에 있음/사화나 진토를 만남을 설명한다.",
      "exceptions_or_counterpoints": "23문단의 이 경우는 앞22문단 뒤에 놓인 연결표현이다. 남자 분기에 인접하지만 실제 적용 범위와 만남의 원국/운 구별은 추가 확인 대상이다.",
      "scope": "병화 개선과 사화/진토 악화의 양면을 보존하며 배타적/충분조건으로 확정하지 않는다.",
      "unknown": "비겁 포함자리·개수·하늘에의 정확한 위치·사화/진토의 원국/운·결혼나이 경계 미확정.",
      "time_scope": "일찍/늦게 결혼이라는 생애 표현. 사화/진토를 만남의 시점이 원국인지 운인지 원문이 명시하지 않음.",
      "gender_scope": "22문단은 남자.23문단의 이 경우는 인접 문맥으로 연결하되 그 밖 성별로 확대하지 않음.",
      "position_scope": "사주 비겁·천간 병화 표현을 보존. 사화/진토 자리와 천간 병화의 구체적 기둥은 미확정.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          19,
          27
        ],
        "xmlParagraphs": [
          267,
          268,
          269,
          270,
          271,
          272,
          273,
          274,
          275
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI17",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "관계",
      4
    ],
    "needles": [
      "배우자에게는 쌀쌀맞지만 육친은 두 팔 걷어붙이고 챙기는 의외의 책임감"
    ],
    "review": {
      "status": "modality_compressed",
      "conditions": "18문단은 배우자와 육친에 다른 태도를 보이는 경우가 있다고 서술한다.",
      "exceptions_or_counterpoints": "원문의 경우라는 표현과13~17문단의 고립/발산 문맥을 보존한다.",
      "scope": "개인에 대한 책임감/가족 태도 관측으로 쓰지 않는 문헌 요약.",
      "unknown": "배우자/육친과의 실제 관계 또는 행동 빈도 미검증.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          13,
          18
        ],
        "xmlParagraphs": [
          261,
          262,
          263,
          264,
          265,
          266
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI18",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "주의",
      0
    ],
    "needles": [
      "너무 강한 힘이라 한번 꺾이면 복구가 매우 어려움 — 힘을 활동적으로 쓰면서도 꺾이지 않게 조절하는 제어력이 반드시 필요"
    ],
    "review": {
      "status": "time_context_lost",
      "conditions": "일주론의 같은 표현은 경자년(2020년) 운세 제목 아래 34–35문단에 위치.",
      "exceptions_or_counterpoints": "고급1의 갑목 일반 실패/재기 설명이 있으나 2020년 문맥의 정확한 표현을 무시기 규칙으로 승인하지 않음.",
      "scope": "제외메모는 경자년 운세 제외라 쓰지만 초안에는 해당 표현이 남음. 문헌 저자가 일반론으로 썼을 가능성과 연도 문맥은 별도 보존.",
      "unknown": "영구 적용 자격 미검증. 후속에서 경자년 단락의 다른 재사용 문장도 전량 점검 필요.",
      "time_scope": "경자년(2020년) 제목 아래34~35문단 재사용; 영구규칙 승인 아님.",
      "gender_scope": "기존 검토의 성별 범위 유지. 명시 없는 성별을 추가하지 않음.",
      "position_scope": "기존 검토의 일간/일지·다른 기둥/월주·운 조건을 그대로 보존하고 실제 명식 조건은 평가하지 않음.",
      "lineage_note": "고급1 계보는 원문 저자 미확정. 일주론/현묘 글은 yavares.tistory.com 같은 계보. 글 수나 재사용을 독립 지지수로 세지 않음."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          33,
          40
        ],
        "xmlParagraphs": [
          281,
          282,
          283,
          284,
          285,
          286,
          287,
          288
        ]
      },
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          7,
          10
        ],
        "xmlParagraphs": [
          466,
          467,
          468,
          469
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN05"
    ],
    "reuseKind": "exact_prior_pointer",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI19",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "주의",
      1
    ],
    "needles": [
      "자존심이 꺾여 집에만 있으면 우울증에 시달리고 집안 식구들을 괴롭히게 됨 — 자기 고립 위험에 항상 유의"
    ],
    "review": {
      "status": "health_claim_and_context",
      "conditions": "14문단은 자존심이 꺾여 집에 있는 상황을,15문단은 자기고립을,17문단은 집안에 가두어 발산하지 못하는 상황을 말한다.",
      "exceptions_or_counterpoints": "단순히 집에 있음과 강제로 가둠을 같게 보지 않는다.16문단의 활동 조언도 질병 치료 지침으로 전환하지 않는다.",
      "scope": "우울증과 가족 괴롭힘을 연결한 저자 주장이 있다는 검수. 의료적 진단/행동 예측 승인 아님.",
      "unknown": "질병 진단·원인·생활조건·행동관측이나 임상 근거가 제시되지 않음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          13,
          18
        ],
        "xmlParagraphs": [
          261,
          262,
          263,
          264,
          265,
          266
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI20",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "주의",
      2
    ],
    "needles": [
      "신강한 명조의 인신충은 중년까지 직업·부부관계가 불리하고, 신약한 명조는 돈·여자 문제로 이동·변동과 가정 불안이 따름 (일지 인목과 편관 신금의 충)"
    ],
    "review": {
      "status": "scenario_conditions_omitted",
      "conditions": "인신충 비교의 신강/신약 갈래. 신강은 월주 인성/비겁과 식상 발산을 향함을 설명하며 일지 비겁 조건에서 중년까지 직업/부부관계를 논한다. 신약 예시는 월주 식상/재성, 일지 인목 의지, 운에서 무신이 오는 조건을 함께 가짐.",
      "exceptions_or_counterpoints": "원문은 그림의 병술월·임자월을 신강/신약 예시로만 쓰고 월주는 해석하지 않는다고 명시.",
      "scope": "충 일반론·무신 운의 개별 예시·월주 예시 범위를 분리. 모든 신약 인신충으로 확대 금지.",
      "unknown": "그림의 실제 명식/시점은 이번 텍스트 검수로 확정하지 않음. 앱 강약 잠정 등급과 저자의 신강/신약 기준을 동일시하지 않음.",
      "time_scope": "신강 갈래의 중년까지(본문25)와 신약 갈래의 무신 운 예시(본문27)를 구분. 서로의 시점을 다른 갈래에 붙이지 않음.",
      "gender_scope": "기존 검토의 성별 범위 유지. 명시 없는 성별을 추가하지 않음.",
      "position_scope": "기존 검토의 일간/일지·다른 기둥/월주·운 조건을 그대로 보존하고 실제 명식 조건은 평가하지 않음.",
      "lineage_note": "unresolved:명리학탐구(고급1). 보관 문서명만으로 저자·원저 계보를 확정하지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          22,
          27
        ],
        "xmlParagraphs": [
          481,
          482,
          483,
          484,
          485,
          486
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN04"
    ],
    "reuseKind": "exact_prior_pointer",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI21",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "주의",
      3
    ],
    "needles": [
      "인성인 해수와 합(인해합목)하여 주변을 의식하는 마음이 커, 민첩한 행동과 과감한 결단이 요구되는 유행에 민감한 사업 추진은 다소 불리"
    ],
    "review": {
      "status": "semantic_partial_reuse",
      "conditions": "고급1의 인해합목 절20~21문단. 인성 해수와 합목·주변 의식·유행/민첩한 결단 사업이라는 범위를 보존한다.",
      "exceptions_or_counterpoints": "IN06 첫 견해의 의미 재사용이고 문구는 다르다. 비교 상대인 남자·식상·금 관성 대안을 같이 읽어야 하며 직접 모순은 아님.",
      "scope": "기존 IN06 그룹의 근거를 다시 쓰는 별도 문자열. 정확문구 일치 보류와 의미 중복을 구분한다.",
      "unknown": "해수 실제 존재·자리/운·합의 성립/합화·사업효과를 이 문장으로 계산하지 않음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일지 인목과 인성 해수 관계. 해수의 구체적 기둥/원국·운 범위가 이 구간에서 확정되지 않음.",
      "lineage_note": "고급1 계보는 원문 저자 미확정. 일주론/현묘 글은 yavares.tistory.com 같은 계보. 글 수나 재사용을 독립 지지수로 세지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          18,
          21
        ],
        "xmlParagraphs": [
          477,
          478,
          479,
          480
        ]
      },
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          9,
          9
        ],
        "xmlParagraphs": [
          257
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN06"
    ],
    "reuseKind": "semantic_partial_reuse",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI22",
    "key": "ilju/갑인",
    "pointer": [
      "distilled",
      "물상"
    ],
    "needles": [
      "바쁘고 활기찬 인목 위에 갑나무가 올려진 형상 — 삶의 변동이 크고 분주하며 기복과 풍파가 많으나 운을 잘 타면 큰 성취를 이룬다. 목이 과도하면 부드러운 나무가 뭉쳐 콘크리트처럼 딱딱해지는 형국."
    ],
    "review": {
      "status": "mixed_sources_condition_omitted",
      "conditions": "전반은 일주론8문단의 인목 위 갑목 물상, 후반은 현묘68~69문단 목 과다의 콘크리트 비유다.",
      "exceptions_or_counterpoints": "운을 잘 타면 성취라는 반대 방향, 현묘67의 다른 연·월·시 요인으로 달라짐을 함께 보존한다.",
      "scope": "같은 현묘 계보의 두 글을 섞은 비유로, 독립 저자2명 증거가 아니다.",
      "unknown": "운을 잘 탐·목 과다의 계산기준과 개인 삶의 기복/성취 미검증.",
      "time_scope": "삶의 변동/운을 잘 탐이라는 미지정 시점. 특정 대운·세운 성과를 계산하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          8,
          8
        ],
        "xmlParagraphs": [
          256
        ]
      },
      {
        "unit": "현묘의 사주 이야기 글모음#0032",
        "doc": "현묘의 사주 이야기 글모음",
        "title": "간뎅이가 부은 사주 (feat. 갑인일주)",
        "archive": "정제본/현묘의 사주 이야기 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          65,
          72
        ],
        "xmlParagraphs": [
          2469,
          2470,
          2471,
          2472,
          2473,
          2474,
          2475,
          2476
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN02"
    ],
    "reuseKind": "shared_evidence_only",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI23",
    "key": "ilju/갑인",
    "pointer": [
      "인용",
      0,
      "text"
    ],
    "needles": [
      "하늘에도 갑목이요, 땅에도 갑목이라 밝고 명랑한 기운이 넘치는 일주입니다. 갑목이 하늘과 땅에 박혔으니 자존심과 자아의 끝판왕이며, 매사에 적극적이고 능동적입니다."
    ],
    "review": {
      "status": "exact_quote_context_retained",
      "conditions": "인용문은 일주론5문단 전체와 정확히 같다.",
      "exceptions_or_counterpoints": "6~7문단의 자기중심성/마찰·배우자 설명을 함께 보존한다.",
      "scope": "IN01의 같은 원문을 인용 문자열로 다시 쓴 것이다. 새 독립 지지0.",
      "unknown": "개인 성향의 사실성·인목 전체가 갑목 하나라는 해석은 승인하지 않음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          4,
          7
        ],
        "xmlParagraphs": [
          252,
          253,
          254,
          255
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN01"
    ],
    "reuseKind": "semantic_partial_reuse",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI24",
    "key": "ilju/갑인",
    "pointer": [
      "인용",
      1,
      "text"
    ],
    "needles": [
      "손해볼 것을 알지만 아닌 건 아니라고 말해야 직성이 풀립니다. 부러지더라도 일단은 부딫칩니다."
    ],
    "review": {
      "status": "exact_substring_condition_omitted",
      "conditions": "현묘70문단의 연속 두 문장과 정확히 일치한다.",
      "exceptions_or_counterpoints": "67문단의 다른 기둥/요인과68문단의 목 과다 단서를 인용에도 동반한다.",
      "scope": "IN02와 동일 원문/계보의 인용. 손상/간 비유를 진단으로 쓰지 않는다.",
      "unknown": "목 과다 기준과 개인 발현·행동 미검증.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "현묘의 사주 이야기 글모음#0032",
        "doc": "현묘의 사주 이야기 글모음",
        "title": "간뎅이가 부은 사주 (feat. 갑인일주)",
        "archive": "정제본/현묘의 사주 이야기 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          65,
          72
        ],
        "xmlParagraphs": [
          2469,
          2470,
          2471,
          2472,
          2473,
          2474,
          2475,
          2476
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN02"
    ],
    "reuseKind": "semantic_partial_reuse",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI25",
    "key": "ilju/갑인",
    "pointer": [
      "인용",
      2,
      "text"
    ],
    "needles": [
      "일지에 비견이 위치하면 고집과 자존심이 강하게 나타나고, 자기중심적 생활태도를 갖게 됩니다."
    ],
    "review": {
      "status": "exact_substring_scope_retained",
      "conditions": "고급1의13문단에 정확히 포함되며 일지 비견 일반 절에 위치한다.",
      "exceptions_or_counterpoints": "일지 비견의 생활/사회/가정 범위와14문단 협력/경쟁 양면을 보존한다.",
      "scope": "갑인만의 고유 특성으로 좁히지 않는 문헌 인용.",
      "unknown": "개인의 고집/자기중심성의 관측 근거 미확정.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "unresolved:명리학탐구(고급1). 보관 문서명만으로 저자·원저 계보를 확정하지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          11,
          14
        ],
        "xmlParagraphs": [
          470,
          471,
          472,
          473
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI26",
    "key": "ilju/갑인",
    "pointer": [
      "관점차이",
      0,
      "견해",
      0,
      "내용"
    ],
    "needles": [
      "인해합목으로 주변을 의식하는 마음이 커 강한 추진력·승부욕을 보이기 힘들어, 유행에 민감한 사업 추진은 다소 불리하다고 봄"
    ],
    "review": {
      "status": "comparison_scope_omitted",
      "conditions": "첫 견해는 인해합목 절의 주변 의식/유행에 민감한 사업 조건. 둘째 견해 원문은 남자·식상·금 관성의 갈래.",
      "exceptions_or_counterpoints": "견해쌍 둘 다 유지. 서로 조건이 달라 직접 모순이나 저자 합의로 판정하지 않음.",
      "scope": "원문 조건이 다른 사업 설명의 비교; 현재 둘째 견해는 식상/관성 대안을 생략.",
      "unknown": "해수 실제 존재 조건을 이 텍스트만으로 계산하지 않음. 저자 기준·개인 적성은 미검증.",
      "time_scope": "기존 검토의 원국/일주 유형·문맥 범위 보존. 실제 시점 조건은 평가하지 않음.",
      "gender_scope": "첫 견해인 고급1의 인해합목 절20~21에는 성별 제한이 없다. 비교상대인 둘째 견해에만 남자·식상·금 관성 갈래가 있다.",
      "position_scope": "기존 검토의 일간/일지·다른 기둥/월주·운 조건을 그대로 보존하고 실제 명식 조건은 평가하지 않음.",
      "lineage_note": "고급1 계보는 원문 저자 미확정. 일주론/현묘 글은 yavares.tistory.com 같은 계보. 글 수나 재사용을 독립 지지수로 세지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          18,
          21
        ],
        "xmlParagraphs": [
          477,
          478,
          479,
          480
        ]
      },
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          9,
          9
        ],
        "xmlParagraphs": [
          257
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN06"
    ],
    "reuseKind": "contained_in_prior_group",
    "comparisonIds": [
      "GI26",
      "GI27"
    ],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI27",
    "key": "ilju/갑인",
    "pointer": [
      "관점차이",
      0,
      "견해",
      1,
      "내용"
    ],
    "needles": [
      "남자는 경쟁하여 쟁취하는 사업길에 어울리며 직장생활 중에도 자기 사업을 일으키는 성향이라고 봄"
    ],
    "review": {
      "status": "comparison_scope_omitted",
      "conditions": "첫 견해는 인해합목 절의 주변 의식/유행에 민감한 사업 조건. 둘째 견해 원문은 남자·식상·금 관성의 갈래.",
      "exceptions_or_counterpoints": "견해쌍 둘 다 유지. 서로 조건이 달라 직접 모순이나 저자 합의로 판정하지 않음.",
      "scope": "원문 조건이 다른 사업 설명의 비교; 현재 둘째 견해는 식상/관성 대안을 생략.",
      "unknown": "해수 실제 존재 조건을 이 텍스트만으로 계산하지 않음. 저자 기준·개인 적성은 미검증.",
      "time_scope": "기존 검토의 원국/일주 유형·문맥 범위 보존. 실제 시점 조건은 평가하지 않음.",
      "gender_scope": "둘째 견해인 일주론9문단은 남자·식상·금 관성 갈래다. 비교상대인 고급1 첫 견해에는 성별 제한이 없다.",
      "position_scope": "기존 검토의 일간/일지·다른 기둥/월주·운 조건을 그대로 보존하고 실제 명식 조건은 평가하지 않음.",
      "lineage_note": "고급1 계보는 원문 저자 미확정. 일주론/현묘 글은 yavares.tistory.com 같은 계보. 글 수나 재사용을 독립 지지수로 세지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          18,
          21
        ],
        "xmlParagraphs": [
          477,
          478,
          479,
          480
        ]
      },
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          9,
          9
        ],
        "xmlParagraphs": [
          257
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN06"
    ],
    "reuseKind": "contained_in_prior_group",
    "comparisonIds": [
      "GI26",
      "GI27"
    ],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI28",
    "key": "ilju/갑인",
    "pointer": [
      "관점차이",
      1,
      "견해",
      0,
      "내용"
    ],
    "needles": [
      "고전은 갑인일주를 '얼어붙은 나무'라 하여 배우자로 적합하지 않다고 봄"
    ],
    "review": {
      "status": "secondary_classical_attribution_unresolved",
      "conditions": "24문단에 고전에는 얼어붙은 나무라 하여 배우자로 부적합하다고 했다는 재인용이 있다.",
      "exceptions_or_counterpoints": "같은 문단 후반 배우자를 애인처럼 대할 때의 대안을 반드시 함께 반환한다.",
      "scope": "현묘 한 저자의 고전 재인용. 실제 고전 원문/판본을 확인한 독립 출처가 아니다.",
      "unknown": "고전 제목·저자·판본·페이지·원래 문맥은 명시되지 않음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "24문단은 성별을 명시하지 않음. 앞뒤 여자/남자 분기와 혼동하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          19,
          27
        ],
        "xmlParagraphs": [
          267,
          268,
          269,
          270,
          271,
          272,
          273,
          274,
          275
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [
      "GI28",
      "GI29"
    ],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI29",
    "key": "ilju/갑인",
    "pointer": [
      "관점차이",
      1,
      "견해",
      1,
      "내용"
    ],
    "needles": [
      "배우자를 애인과 같은 자세로 대하면 의외의 궁합을 발휘할 수 있다는 현대적 재해석 병기"
    ],
    "review": {
      "status": "same_author_counterpoint",
      "conditions": "24문단 후반은 배우자를 애인처럼 대한다면 의외의 궁합을 발휘할 수 있다는 조건부 대안이다.",
      "exceptions_or_counterpoints": "같은 문단의 고전 재인용과 쌍으로 보존. 현대적 재해석은 증류자의 표제이며 별도 현대 출처가 아니다.",
      "scope": "한 저자/한 문단의 대조. 고전 대 현대 두 독립 계보의 합의/충돌로 세지 않는다.",
      "unknown": "태도 변화의 정의·효과·개인 궁합 검증은 없음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "원문24문단에 성별 제한 없음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          19,
          27
        ],
        "xmlParagraphs": [
          267,
          268,
          269,
          270,
          271,
          272,
          273,
          274,
          275
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [
      "GI28",
      "GI29"
    ],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI30",
    "key": "ilju/갑인",
    "pointer": [
      "관점차이",
      2,
      "견해",
      0,
      "내용"
    ],
    "needles": [
      "십신·지장간·합충의 구조 분석 중심"
    ],
    "review": {
      "status": "editorial_methodology_summary",
      "conditions": "원문 분석단계와 각 절 제목에서 십신/지장간/합충 구조를 실제 확인한다.",
      "exceptions_or_counterpoints": "갑목 물상·성향 서술도7~10문단에 있으므로 방법을 구조 분석만으로 배타 분류하지 않는다.",
      "scope": "저자가 직접 선언한 학파명이 아닌 증류자의 서술방법 요약이다.",
      "unknown": "다른 방법과 우열·완전성·예측력은 검증하지 않음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "unresolved:명리학탐구(고급1). 보관 문서명만으로 저자·원저 계보를 확정하지 않음."
    },
    "sources": [
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          2,
          6
        ],
        "xmlParagraphs": [
          461,
          462,
          463,
          464,
          465
        ]
      },
      {
        "unit": "명리학탐구(고급1) 게시판 글모음#0018",
        "doc": "명리학탐구(고급1) 게시판 글모음",
        "title": "320.일주분석(3) - 식상과 재성에 가치를 두는 갑인일주",
        "archive": "정제본/명리학탐구(고급1) 게시판 글모음.docx",
        "lineage": "unresolved:명리학탐구(고급1)",
        "bodyParagraphs": [
          11,
          27
        ],
        "xmlParagraphs": [
          470,
          471,
          472,
          473,
          474,
          475,
          476,
          477,
          478,
          479,
          480,
          481,
          482,
          483,
          484,
          485,
          486
        ]
      }
    ],
    "matchScope": "gapin_block_only",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [
      "GI30",
      "GI31",
      "GI32"
    ],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI31",
    "key": "ilju/갑인",
    "pointer": [
      "관점차이",
      2,
      "견해",
      1,
      "내용"
    ],
    "needles": [
      "물상·십이운성·통계적 경향 중심"
    ],
    "review": {
      "status": "statistical_label_without_statistics",
      "conditions": "물상/건록/육친 설명과21/27문단의 통계적으로라는 표현이 확인된다.",
      "exceptions_or_counterpoints": "통계적으로라는 어휘가 실제 통계 연구·분모·대조군을 뜻하지 않는다. 십신·지장간도47~57문단에 있어 배타 방법론 아님.",
      "scope": "통계적 경향 중심은 증류자 분류이며 실증 검증/통계 정확도 승인 아님.",
      "unknown": "관측 표본/수집 방법/빈도/추정 오차가 없다.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          4,
          12
        ],
        "xmlParagraphs": [
          252,
          253,
          254,
          255,
          256,
          257,
          258,
          259,
          260
        ]
      },
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          19,
          27
        ],
        "xmlParagraphs": [
          267,
          268,
          269,
          270,
          271,
          272,
          273,
          274,
          275
        ]
      },
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          47,
          64
        ],
        "xmlParagraphs": [
          295,
          296,
          297,
          298,
          299,
          300,
          301,
          302,
          303,
          304,
          305,
          306,
          307,
          308,
          309,
          310,
          311,
          312
        ]
      }
    ],
    "matchScope": "gapin_block_only",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [
      "GI30",
      "GI31",
      "GI32"
    ],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI32",
    "key": "ilju/갑인",
    "pointer": [
      "관점차이",
      2,
      "견해",
      2,
      "내용"
    ],
    "needles": [
      "오행 목(간·용기)의 물상으로 성정을 풀이 — 상호보완적"
    ],
    "review": {
      "status": "metaphor_and_complementarity_unverified",
      "conditions": "목·간·용기의 연관 비유는 원문에 있고57문단은 이렇게 단순화하기 힘들다는 단서를 둔다.",
      "exceptions_or_counterpoints": "67문단의 다른 기둥/요인과68문단의 목 과다 조건을 보존. 다른 글과 상호보완적이라는 관계는 증류자의 평가다.",
      "scope": "의학적 간 기능/용기 인과를 승인하지 않으며 현묘 두 글은 같은 계보다.",
      "unknown": "간 건강 진단·개인 용기·상호보완성의 평가기준 미검증.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "현묘의 사주 이야기 글모음#0032",
        "doc": "현묘의 사주 이야기 글모음",
        "title": "간뎅이가 부은 사주 (feat. 갑인일주)",
        "archive": "정제본/현묘의 사주 이야기 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          12,
          16
        ],
        "xmlParagraphs": [
          2416,
          2417,
          2418,
          2419,
          2420
        ]
      },
      {
        "unit": "현묘의 사주 이야기 글모음#0032",
        "doc": "현묘의 사주 이야기 글모음",
        "title": "간뎅이가 부은 사주 (feat. 갑인일주)",
        "archive": "정제본/현묘의 사주 이야기 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          32,
          64
        ],
        "xmlParagraphs": [
          2436,
          2437,
          2438,
          2439,
          2440,
          2441,
          2442,
          2443,
          2444,
          2445,
          2446,
          2447,
          2448,
          2449,
          2450,
          2451,
          2452,
          2453,
          2454,
          2455,
          2456,
          2457,
          2458,
          2459,
          2460,
          2461,
          2462,
          2463,
          2464,
          2465,
          2466,
          2467,
          2468
        ]
      },
      {
        "unit": "현묘의 사주 이야기 글모음#0032",
        "doc": "현묘의 사주 이야기 글모음",
        "title": "간뎅이가 부은 사주 (feat. 갑인일주)",
        "archive": "정제본/현묘의 사주 이야기 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          65,
          72
        ],
        "xmlParagraphs": [
          2469,
          2470,
          2471,
          2472,
          2473,
          2474,
          2475,
          2476
        ]
      }
    ],
    "matchScope": "gapin_block_only",
    "priorReviewIds": [
      "IN02"
    ],
    "reuseKind": "shared_evidence_only",
    "comparisonIds": [
      "GI30",
      "GI31",
      "GI32"
    ],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI33",
    "key": "ilju/갑인",
    "pointer": [
      "기타",
      0
    ],
    "needles": [
      "유명인: 김두관 의원, 성시경, 박신혜 (출처: 일주론 글모음)"
    ],
    "review": {
      "status": "named_examples_unverified",
      "conditions": "28문단에 김두관 의원·성시경·박신혜를 갑인 유명인으로 나열한다.",
      "exceptions_or_counterpoints": "명단이 존재한다는 확인과 세 사람의 실제 출생자료/일주 확인을 구별한다.",
      "scope": "실명은 이미 공개된 원문/초안의 귀속 확인에만 사용. 독립 관측 사례/학습 라벨0.",
      "unknown": "정확한 출생지·생시·출처·시간대와 명식은 이 구간에 없음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          28,
          28
        ],
        "xmlParagraphs": [
          276
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI34",
    "key": "ilju/갑인",
    "pointer": [
      "기타",
      1
    ],
    "needles": [
      "갑인은 10천간의 시작인 갑목의 기상을 일지로 내려받은, 갑목의 정통과 뿌리를 가진 간지 — 새로운 세상은 갑인일주로부터 시작된다는 서술 (현묘의 사주 이야기)"
    ],
    "review": {
      "status": "rhetorical_claim_not_prediction",
      "conditions": "82~86문단은 갑목의 시작·정통/뿌리·새 세상이라는 수사다.",
      "exceptions_or_counterpoints": "67문단 다른 기둥/요인과73~81의 용기/주변인 대조 문맥을 보존한다.",
      "scope": "새 세상을 만드는 개인/사건 예측 규칙이나 관측 역사의 정답이 아니다.",
      "unknown": "새로운 세상/시작/정통의 관측 정의·역사적 검증 없음.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "현묘의 사주 이야기 글모음#0032",
        "doc": "현묘의 사주 이야기 글모음",
        "title": "간뎅이가 부은 사주 (feat. 갑인일주)",
        "archive": "정제본/현묘의 사주 이야기 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          65,
          86
        ],
        "xmlParagraphs": [
          2469,
          2470,
          2471,
          2472,
          2473,
          2474,
          2475,
          2476,
          2477,
          2478,
          2479,
          2480,
          2481,
          2482,
          2483,
          2484,
          2485,
          2486,
          2487,
          2488,
          2489,
          2490
        ]
      }
    ],
    "matchScope": "known_wording",
    "priorReviewIds": [
      "IN02"
    ],
    "reuseKind": "shared_evidence_only",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  },
  {
    "id": "GI35",
    "key": "ilju/갑인",
    "pointer": [
      "기타",
      2
    ],
    "needles": [
      "참고문헌(원문 표기): 박청화 『박청화의 강의노트』, 강헌 『명리 기본편, 심화편』 등"
    ],
    "review": {
      "status": "bibliography_not_claim_level_provenance",
      "conditions": "원문 참고자료에 박청화 강의노트, 강헌 명리 기본편/심화편과 두 방송/강의가 표기되어 있다.",
      "exceptions_or_counterpoints": "원문은 각 문장의 책/쪽수를 연결하지 않는다. 참고문헌4개를 각 주장 독립4지지로 세지 않는다.",
      "scope": "현묘 글의 일반 참고문헌 목록 보존. 원저자/문장별 계보 확정 아님.",
      "unknown": "책 판본·페이지·인용구·실제 참조/원저자 경로 미확인.",
      "time_scope": "원국/일주 유형 일반 서술. 적용 시점·운의 실제 입력은 평가하지 않음.",
      "gender_scope": "성별을 제한하지 않은 저자의 서술. 개인 성별로 발현을 추정하지 않음.",
      "position_scope": "일간 갑목·일지 인목의 문헌 설명. 다른 기둥의 조건 충족은 미계산.",
      "lineage_note": "yavares.tistory.com. 일주론 /59와 현묘 /388은 같은 계보이며 서로 독립 저자 지지 아님."
    },
    "sources": [
      {
        "unit": "일주론 글모음#0002",
        "doc": "일주론 글모음",
        "title": "갑인일주(甲寅日柱) <일주론>",
        "archive": "정제본/일주론 글모음.docx",
        "lineage": "yavares.tistory.com",
        "bodyParagraphs": [
          60,
          64
        ],
        "xmlParagraphs": [
          308,
          309,
          310,
          311,
          312
        ]
      }
    ],
    "matchScope": "gapin_block_only",
    "priorReviewIds": [],
    "reuseKind": "new",
    "comparisonIds": [],
    "sourceConditionStatus": "not_evaluated",
    "personalApplication": "withheld",
    "trainingEligible": false,
    "probability": null
  }
];
