"""Browser projection of PR214's validated structural references; no personal claims."""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'docs/knowledge-model'))
from gapin_structure_review import load_review

TARGET = ROOT / 'dosa-app/engine/src/gapinStructureData.js'
LABELS = ['일주 구성', '일지의 대표 십신', '지장간 구성', '십이운성 이름', '식신과 상관의 분류']
LIMITS = [
    '글자의 구성을 설명하며 개인의 성격을 판단하지 않아요.',
    '인목 전체나 지장간 전부가 비견이라는 뜻은 아니에요.',
    '구성과 이름만 설명해요. 각 글자의 힘이나 재물복을 뜻하지 않아요.',
    '건록이라는 이름만으로 강약·독립성·성공을 판단하지 않아요.',
    '갑목이 무엇을 식신·상관으로 분류하는지 설명해요. 직업 풀이에서 식상을 어디까지 세는지는 확인 중이에요.',
]


def render():
    review = load_review(ROOT)
    items = []
    for claim, label, limit in zip(review['claims'], LABELS, LIMITS, strict=True):
        # The reviewed source layer already exists. Do not duplicate its archive
        # coordinates/bibliography in the browser or turn source display into a gate.
        items.append(dict(id=claim['id'], label=label, text=claim['text'], scope=claim['scope'],
                          limits=claim['limits'], displayLimit=limit,
                          delivery=claim['delivery'], personalApplication='withheld',
                          trainingEligible=False, probability=None))
    return '// Generated by scripts/build_gapin_structure_data.py from the validated PR214 review.\nexport default ' + json.dumps(items, ensure_ascii=False, indent=2) + ';\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    expected = render()
    if args.check:
        if TARGET.read_text(encoding='utf-8') != expected:
            raise ValueError('Gapin structure projection drift')
        print('5 structural definitions projected; existing archival review preserved')
    else:
        TARGET.write_text(expected, encoding='utf-8')
