"""Separate projection of the pinned Gapin review; never alters archival drafts."""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'docs/knowledge-model'))
import gapin_sentence_review as review

TARGET = ROOT / 'dosa-app/engine/src/gapinSentenceData.js'


def render():
    data = json.loads((ROOT / 'docs/knowledge-model/data/gapin_sentence_review.json').read_text(encoding='utf-8'))
    review.validate(data)
    spans = {s['id']: s for s in data['spans']}
    items = []
    for item in data['items']:
        if item['id'] == 'GI36':
            continue  # Editorial exclusion note is not a personal claim.
        sources = []
        for sid in item['evidence']:
            span, unit = spans[sid], data['source_units'][spans[sid]['unit']]
            sources.append(dict(unit=span['unit'], doc=span['unit'].rsplit('#', 1)[0],
                title=unit['title'], archive=unit['archive_path'], lineage=unit['lineage'],
                bodyParagraphs=span['body_paragraphs'], xmlParagraphs=[p['xml_paragraph'] for p in span['paragraphs']]))
        items.append(dict(id=item['id'], key='ilju/갑인', pointer=item['pointer'],
            needles=[item['draft_value']], review=item['review'], sources=sources,
            matchScope='gapin_block_only' if item['id'] in {'GI30', 'GI31', 'GI32', 'GI35'} else 'known_wording',
            priorReviewIds=item['prior_review_ids'], reuseKind=item['reuse_kind'],
            comparisonIds=next((g['member_item_ids'] for g in data['perspective_groups'] if item['id'] in g['member_item_ids']), []),
            sourceConditionStatus='not_evaluated', personalApplication='withheld', trainingEligible=False, probability=None))
    return '// Generated by scripts/build_gapin_sentence_policy.py; archival review remains unchanged.\nexport default ' + json.dumps(items, ensure_ascii=False, indent=2) + ';\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    expected = render()
    if args.check:
        if TARGET.read_text(encoding='utf-8') != expected:
            raise ValueError('Gapin sentence projection drift')
        print('35 Gapin review records verified; personal inference withheld')
    else:
        TARGET.write_text(expected, encoding='utf-8')
