"""Compare the scoped hidden-stem overlap repair and audit stage retrieval.

Run after corpus regeneration with --output /tmp/hidden-stages.json.
Both historical builders use their historical taxonomy/gates; no output maps,
D5, P2, engine tables or probabilities are generated by this measurement.
"""
import argparse
from collections import Counter, defaultdict
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
from types import ModuleType
from unittest.mock import patch

REPO = Path(__file__).resolve().parents[2]
LEGACY = REPO / "정제/_현황판"
BASE = "13255abe7512e7ac265a4cc3ec3814f2de11aa36"


def sha(raw):
    return hashlib.sha256(raw.replace(b"\r\n", b"\n")).hexdigest()


def source(name, baseline):
    path = LEGACY / (name + ".py")
    return (subprocess.check_output(["git", "show", f"{BASE}:{path.relative_to(REPO).as_posix()}"], cwd=REPO)
            if baseline else path.read_bytes())


def load_pair(baseline):
    raw_cmap = source("build_concept_map", baseline)
    raw_neuron = source("build_neuron_map", baseline)
    read_text = Path.read_text

    def read_taxonomy(path, *args, **kwargs):
        if path.resolve() == LEGACY / "build_concept_map.py":
            return raw_cmap.decode("utf-8")
        return read_text(path, *args, **kwargs)

    modules = []
    with patch.object(Path, "read_text", read_taxonomy):
        for name, raw in (("build_neuron_map", raw_neuron), ("build_concept_map", raw_cmap)):
            module = ModuleType(name + ("_baseline" if baseline else "_current"))
            module.__file__ = str(LEGACY / (name + ".py"))
            exec(compile(raw, module.__file__, "exec"), module.__dict__)
            modules.append(module)
    neuron, cmap = modules
    cmap._bnm = neuron  # Never bind old concept-map code to the current gate.
    if neuron.TAXONOMY != cmap.TAXONOMY:
        raise ValueError("The two builders loaded different taxonomies")
    return neuron, cmap, {"neuron": sha(raw_neuron), "concept_map": sha(raw_cmap)}



def delta(before, after):
    return {c: {"before": len(before.get(c, set())), "after": len(after.get(c, set())),
                "added_ids": sorted(after.get(c, set()) - before.get(c, set())),
                "removed_ids": sorted(before.get(c, set()) - after.get(c, set()))}
            for c in sorted(set(before) | set(after)) if before.get(c, set()) != after.get(c, set())}


def run_pair(pair, rows, reader, label):
    neuron, cmap, _ = pair
    neuron_hits = defaultdict(set)
    for row in rows:
        for concept in neuron.concepts_in(row["text"]):
            neuron_hits[concept].add(row["q"]["para_id"])
    with patch.object(reader, "문단들", lambda **kwargs: iter(rows)):
        built, _, n = cmap.build()
    if n != len(rows):
        raise ValueError("Corpus changed")
    cmap_hits = {name: {q["para_id"] for q, _ in matches}
                 for groups in built.values() for concepts in groups.values() for name, matches in concepts.items()}
    print(f"{label}: both builders complete", flush=True)
    return {"neuron": neuron_hits, "concept_map": cmap_hits}


def measure():
    sys.path.insert(0, str(LEGACY))
    import 코퍼스 as reader
    rows = list(reader.문단들(제목포함=True))
    if not rows or len({r["q"]["para_id"] for r in rows}) != len(rows):
        raise ValueError("Empty corpus or duplicate paragraph IDs")
    before, after = load_pair(True), load_pair(False)
    if before[1].TAXONOMY != after[1].TAXONOMY or before[2]["concept_map"] != after[2]["concept_map"]:
        raise ValueError("Unexpected taxonomy or concept-map change")
    if "지장간" in before[0].concepts_in("시지장간") or "지장간" not in after[0].concepts_in("시지장간"):
        raise ValueError("Historical/current overlap behavior not isolated")
    unchanged = {}
    for path in ("dosa-app/engine/src/tables.js", "docs/knowledge-model/chart_context.mjs"):
        raw = (REPO / path).read_bytes()
        old = subprocess.check_output(["git", "show", f"{BASE}:{path}"], cwd=REPO)
        if sha(raw) != sha(old):
            raise ValueError("Unexpected engine/observation change: " + path)
        unchanged[path] = sha(raw)

    baseline = run_pair(before, rows, reader, "baseline")
    current = run_pair(after, rows, reader, "current")
    changes = {builder: delta(baseline[builder], current[builder]) for builder in baseline}
    expected = {"ST-P1078-05", "ST-P1078-10", "T-53ebbe2d99-0000", "T-53ebbe2d99-0003"}
    if changes["concept_map"] or set(changes["neuron"]) != {"지장간"}:
        raise ValueError("Unexpected unrelated concept change")
    hidden = changes["neuron"]["지장간"]
    if set(hidden["added_ids"]) != expected or hidden["removed_ids"]:
        raise ValueError("Unexpected hidden-stem change")
    if current["neuron"]["지장간"] != current["concept_map"]["지장간"]:
        raise ValueError("Hidden-stem builders still disagree")
    if load_pair(True)[2] != before[2] or load_pair(False)[2] != after[2]:
        raise ValueError("Builder code changed during measurement")

    aliases = ["여기", "중기", "정기", "본기", "正氣"]
    raw_counts = {}
    for alias in aliases:
        matches = [r for r in rows if alias in r["text"]]
        gate = after[0].AMBIG_RE.get(alias)
        raw_counts[alias] = {
            "substring_rows": len(matches),
            "substring_occurrences": sum(r["text"].count(alias) for r in matches),
            "paragraph_gate_present": gate is not None,
            "paragraph_gate_pass_rows": sum(not gate or bool(gate.search(r["text"])) for r in matches),
        }
    probes = {}
    for alias in ("초기", "餘氣", "本氣"):
        ids = {r["q"]["para_id"] for r in rows if alias in r["text"]}
        probes[alias] = {"applied": False, "substring_rows": len(ids),
                        "currently_unrecalled_rows": {b: len(ids - h["여기·중기·정기"])
                                                      for b, h in current.items()}}
    case_ids = ["PL-GANJI-P025-01", "PL-ILJU-P002-13", "CT-P005-07", "ST-P0589-08",
                "DR-P625-07", "PL-SINSAL-P001-03", "PL-JEOLGI-P014-03", "CT-P024-09", "CT-P027-16"]
    by_id = {r["q"]["para_id"]: r for r in rows}
    if not set(case_ids) <= by_id.keys():
        raise ValueError("Reviewed stage paragraph missing")
    cases = {pid: {"file": by_id[pid]["post"].get("file"),
                   "stage_hits": {b: pid in h["여기·중기·정기"] for b, h in current.items()},
                   "aliases_in_text": [a for a in aliases if a in by_id[pid]["text"]]}
             for pid in case_ids}
    subjects = ("지장간", "여기·중기·정기", "연지", "월지", "일지", "시지")
    inputs = ["build_dashboard.py", "ingest_transcripts.py", "코퍼스.py",
              "data/posts_all.jsonl", "data/paras_all.jsonl", "data/전사_글.jsonl", "data/전사_문단.jsonl"]
    return {
        "schema_version": 1, "base_commit": BASE,
        "scope": "Legacy topic retrieval; stage false positives are reviewed, not relabeled or learned",
        "corpus_rows": len(rows), "reader_labels": dict(Counter(r["출처종"] for r in rows)),
        "title_included": True, "gist_included": False,
        "independent_evidence_count": None, "probability": None, "training_labels": False,
        "actual_alias_additions": [], "actual_alias_removals": [],
        "code": {"before": before[2], "after": after[2], "unchanged": unchanged},
        "measurement_sha256": sha(Path(__file__).read_bytes()),
        "counts": {label: {b: {c: len(h[c]) for c in subjects} for b, h in pairs.items()}
                   for label, pairs in (("before", baseline), ("after", current))},
        "actual_concept_assignment_changes": changes,
        "stage_alias_occurrences": raw_counts, "unregistered_spellings": probes,
        "reviewed_stage_cases": cases,
        "stage_builder_differences": {
            "neuron_only_ids": sorted(current["neuron"]["여기·중기·정기"] - current["concept_map"]["여기·중기·정기"]),
            "concept_map_only_ids": sorted(current["concept_map"]["여기·중기·정기"] - current["neuron"]["여기·중기·정기"])},
        "inputs": [{"path": (LEGACY / p).relative_to(REPO).as_posix(), "sha256": sha((LEGACY / p).read_bytes())}
                   for p in inputs],
        "corpus_sha256": sha(json.dumps([[r["q"]["para_id"], r["text"], r["출처종"]] for r in rows],
                                        ensure_ascii=False, separators=(",", ":")).encode()),
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    result = measure()
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"counts": result["counts"], "changes": result["actual_concept_assignment_changes"],
                      "stage_differences": result["stage_builder_differences"]}, ensure_ascii=False))
