"""Corpus-backed checks for coverage, provenance and safe review-only retrieval."""
import copy
import hashlib
import io
import json
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest
import xml.etree.ElementTree as ET
import zipfile

import gapin_sentence_review as subject


class GapinSentenceReviewTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.review = subject.load_review()

    def altered(self):
        return copy.deepcopy(self.review)

    def fixture(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        repo = Path(temporary.name) / 'repo'
        repo.mkdir()
        for rel in set(self.review['inputs']) | set(self.review['archives']):
            target = repo / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(subject.REPO / rel, target)
        return repo

    def rewrite_json_input(self, repo, review, rel, value):
        raw = json.dumps(value, ensure_ascii=False).encode()
        (repo / rel).write_bytes(raw)
        review['inputs'][rel] = hashlib.sha256(raw).hexdigest()

    def rewrite_archive_paragraph(self, repo, review, rel, xml_paragraph):
        with zipfile.ZipFile(repo / rel) as source:
            members = {entry.filename: source.read(entry) for entry in source.infolist()}
        namespace = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
        document = ET.fromstring(members['word/document.xml'])
        paragraph = list(document.iter(namespace + 'p'))[xml_paragraph - 1]
        texts = list(paragraph.iter(namespace + 't'))
        self.assertTrue(texts)
        texts[0].text = (texts[0].text or '') + ' CORPUS_CHANGED'
        members['word/document.xml'] = ET.tostring(document, encoding='utf-8', xml_declaration=True)
        output = io.BytesIO()
        with zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED) as archive:
            for name, raw in members.items():
                archive.writestr(name, raw)
        raw = output.getvalue()
        (repo / rel).write_bytes(raw)
        review['archives'][rel] = hashlib.sha256(raw).hexdigest()

    def test_actual_inventory_and_prior_overlap(self):
        self.assertEqual(len(self.review['inventory']['entries']), 65)
        self.assertEqual(len(self.review['items']), 36)
        self.assertEqual(sum(e['role'] == 'claim' for e in self.review['inventory']['entries']), 35)
        self.assertEqual(sum(e['role'] == 'exclusion_note' for e in self.review['inventory']['entries']), 1)
        exact = [i for i in self.review['items'] if i['reuse_kind'] == 'exact_prior_pointer']
        grouped = [i for i in self.review['items'] if i['reuse_kind'] == 'contained_in_prior_group']
        partial = [i for i in self.review['items'] if i['reuse_kind'] == 'semantic_partial_reuse']
        self.assertEqual(len(exact), 5)
        self.assertEqual(len(grouped), 2)
        self.assertEqual({i['prior_review_ids'][0] for i in exact}, {'IN01', 'IN02', 'IN03', 'IN04', 'IN05'})
        self.assertEqual([i['pointer'] for i in partial],
                         [['distilled', '핵심'], ['distilled', '성격', 6], ['distilled', '주의', 3],
                          ['인용', 0, 'text'], ['인용', 1, 'text']])
        self.assertEqual([i['prior_review_ids'] for i in partial],
                         [['IN01', 'IN05'], ['IN02'], ['IN06'], ['IN01'], ['IN02']])
        self.assertEqual(sum(i['reuse_kind'] == 'shared_evidence_only' for i in self.review['items']), 6)
        self.assertEqual(self.review['inventory']['counts']['new_review_items'], 29)
        self.assertEqual(self.review['inventory']['counts']['cumulative_personality_review_items'], 9)

    def test_exact_docx_physical_paragraph_is_reproducible(self):
        # Independent XML access: check a known physical locator and original
        # quotation, not only values generated by the review parser.
        rel = '정제본/일주론 글모음.docx'
        with zipfile.ZipFile(subject.REPO / rel) as archive:
            document = ET.fromstring(archive.read('word/document.xml'))
        ns = {'w': 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'}
        paragraphs = document.findall('.//w:p', ns)
        text = lambda p: ''.join(node.text or '' for node in p.findall('.//w:t', ns)).strip()
        self.assertEqual(text(paragraphs[246]), '갑인일주(甲寅日柱) <일주론>')
        self.assertEqual(text(paragraphs[252]), '하늘에도 갑목이요, 땅에도 갑목이라 밝고 명랑한 기운이 넘치는 일주입니다. 갑목이 하늘과 땅에 박혔으니 자존심과 자아의 끝판왕이며, 매사에 적극적이고 능동적입니다.')
        physical = [p for span in self.review['spans'] if span['unit'] == '일주론 글모음#0002'
                    for p in span['paragraphs'] if p['xml_paragraph'] == 253]
        self.assertTrue(physical)
        self.assertTrue(all(p['text'] == text(paragraphs[252]) for p in physical))

    def test_missing_leaf_is_detected_without_relying_on_digest(self):
        review = self.altered()
        review['inventory']['entries'].pop()
        with self.assertRaisesRegex(ValueError, 'inventory is incomplete'):
            subject.validate(review)

    def test_duplicate_pointer_and_boolean_index_are_rejected(self):
        review = self.altered()
        extra = copy.deepcopy(review['inventory']['entries'][0])
        extra['id'] = 'EXTRA'
        review['inventory']['entries'].append(extra)
        with self.assertRaisesRegex(ValueError, 'Duplicate inventory pointer'):
            subject.validate(review)
        review = self.altered()
        entry = next(e for e in review['inventory']['entries'] if e['pointer'] == ['distilled', '성격', 0])
        entry['pointer'][-1] = False
        with self.assertRaisesRegex(ValueError, 'Invalid list pointer'):
            subject.validate(review)

    def test_omitted_item_and_metadata_promotion_are_rejected(self):
        review = self.altered()
        review['items'].pop()
        with self.assertRaisesRegex(ValueError, 'Review item coverage changed'):
            subject.validate(review)
        review = self.altered()
        entry = next(e for e in review['inventory']['entries'] if e['role'] == 'topic_label')
        entry['review_item_id'] = review['items'][0]['id']
        with self.assertRaisesRegex(ValueError, 'Metadata promoted'):
            subject.validate(review)

    def test_partial_reuse_cannot_be_counted_as_unrelated_new_claim(self):
        review = self.altered()
        entry = next(e for e in review['inventory']['entries'] if e['pointer'] == ['distilled', '주의', 3])
        item = next(i for i in review['items'] if i['id'] == entry['review_item_id'])
        for value in (entry, item):
            value['prior_review_ids'] = ['IN05']
        with self.assertRaisesRegex(ValueError, 'Invalid semantic reuse binding'):
            subject.validate(review)

    def test_review_types_and_no_inference_policy(self):
        for field, value, message in (
            ('source_review_complete', 1, 'Invalid source review state'),
            ('training_eligible', 0, 'Cannot promote'),
            ('personal_application', 'approved', 'Cannot promote'),
            ('probability', 0.5, 'Cannot promote'),
        ):
            with self.subTest(field=field):
                review = self.altered()
                review['items'][0][field] = value
                with self.assertRaisesRegex(ValueError, message):
                    subject.validate(review)
        review = self.altered()
        review['training_eligible'] = False
        with self.assertRaisesRegex(ValueError, 'No personal inference'):
            subject.validate(review)

    def test_explicit_source_cannot_be_replaced_by_another_draft_source(self):
        review = self.altered()
        item = next(i for i in review['items'] if i['pointer'] == ['인용', 2, 'text'])
        wrong = next(s for s in review['spans'] if s['unit'] == '일주론 글모음#0002')
        item['evidence'] = [wrong['id']]
        with self.assertRaisesRegex(ValueError, 'Explicit source attribution changed'):
            subject.validate(review)

    def test_source_paragraph_mutation_is_detected_after_rehashed_archive(self):
        repo, review = self.fixture(), self.altered()
        span = next(s for s in review['spans'] if s['unit'] == '일주론 글모음#0002'
                    and any(p['xml_paragraph'] == 253 for p in s['paragraphs']))
        rel = review['source_units'][span['unit']]['archive_path']
        self.rewrite_archive_paragraph(repo, review, rel, 253)
        with self.assertRaisesRegex(ValueError, 'Source span changed|Source preceding context changed|Source following context changed'):
            subject.validate(review, repo)

    def test_adjacent_context_is_required_and_reproduced(self):
        review = self.altered()
        span = next(span for span in review['spans'] if span['context_after'])
        span['context_after'][0]['text'] = 'A replacement context would hide exceptions.'
        with self.assertRaisesRegex(ValueError, 'Source following context changed'):
            subject.validate(review)
        review = self.altered()
        span = next(span for span in review['spans'] if span['context_before'])
        span['context_before'] = []
        with self.assertRaisesRegex(ValueError, 'Source preceding context changed'):
            subject.validate(review)

    def test_shared_source_is_not_semantic_reuse_or_independent_support(self):
        review = self.altered()
        item = next(i for i in review['items'] if i['pointer'] == ['distilled', '성격', 2])
        entry = next(e for e in review['inventory']['entries'] if e['review_item_id'] == item['id'])
        # This sentence occurs inside the same old span as IN01, but it was
        # not itself IN01's reviewed claim or pointer.
        self.assertEqual(item['reuse_kind'], 'shared_evidence_only')
        self.assertEqual(item['prior_review_ids'], ['IN01'])
        for value in (item, entry):
            value['prior_review_ids'] = ['IN04']
        with self.assertRaisesRegex(ValueError, 'Prior evidence overlap not reproduced'):
            subject.validate(review)
        review = self.altered()
        review['independent_support_count'] = 3
        with self.assertRaisesRegex(ValueError, 'No personal inference'):
            subject.validate(review)

    def test_counts_and_all_ilju_inventory_are_reproduced(self):
        review = self.altered()
        review['inventory']['counts']['new_review_items'] = 36
        with self.assertRaisesRegex(ValueError, 'Inventory counts changed'):
            subject.validate(review)
        repo, review = self.fixture(), self.altered()
        (repo / 'dosa-app/kb/distilled/ilju/extra.json').write_text('{}', encoding='utf-8')
        with self.assertRaisesRegex(ValueError, 'Ilju input inventory changed'):
            subject.validate(review, repo)

    def test_physical_locator_and_span_bounds_are_checked(self):
        review = self.altered()
        review['spans'][0]['paragraphs'][0]['xml_paragraph'] += 1
        with self.assertRaisesRegex(ValueError, 'Source span changed'):
            subject.validate(review)
        review = self.altered()
        review['spans'][0]['body_paragraphs'][0] = True
        with self.assertRaisesRegex(ValueError, 'Invalid body range'):
            subject.validate(review)

    def test_required_input_and_changed_corpus_are_checked(self):
        review = self.altered()
        del review['inputs'][subject.PRIOR]
        with self.assertRaisesRegex(ValueError, 'Missing required input'):
            subject.validate(review)
        repo, review = self.fixture(), self.altered()
        (repo / subject.DRAFT).write_text('{}', encoding='utf-8')
        with self.assertRaisesRegex(ValueError, 'Input changed'):
            subject.validate(review, repo)

    def test_catalog_identity_is_reproduced_after_rehash(self):
        repo, review = self.fixture(), self.altered()
        catalog = json.loads((repo / subject.CATALOG).read_text(encoding='utf-8'))
        row = next(row for row in catalog if row['key'] == '일주론 글모음#0002')
        row['title'] = 'Unrelated article'
        self.rewrite_json_input(repo, review, subject.CATALOG, catalog)
        with self.assertRaisesRegex(ValueError, 'Source catalog/index provenance changed'):
            subject.validate(review, repo)

    def test_path_traversal_and_symlink_escape_are_rejected(self):
        review = self.altered()
        review['inputs']['../outside.json'] = '0' * 64
        with self.assertRaisesRegex(ValueError, 'Path escapes repository'):
            subject.validate(review)
        repo, review = self.fixture(), self.altered()
        outside = repo.parent / 'outside'
        outside.mkdir()
        (outside / 'data.json').write_text('{}', encoding='utf-8')
        # A Windows directory junction does not need file-symlink privileges.
        # Node is already required by the repository gates; on POSIX this
        # creates a real directory symlink. Neither platform skips the check.
        subprocess.run([
            'node', '-e',
            "require('node:fs').symlinkSync(process.argv[1], process.argv[2], 'junction')",
            str(outside.resolve()), str(repo / 'link'),
        ], check=True, capture_output=True, timeout=10)
        review['inputs']['link/data.json'] = hashlib.sha256(b'{}').hexdigest()
        with self.assertRaisesRegex(ValueError, 'Path escapes repository'):
            subject.validate(review, repo)

    def test_perspective_retrieval_retains_opposing_member_and_detaches(self):
        group = self.review['perspective_groups'][0]
        result = subject.retrieve(group['member_item_ids'][0])
        self.assertEqual([i['id'] for i in result['comparison_items']], group['member_item_ids'])
        self.assertEqual(result['perspective_groups'], [group])
        self.assertEqual({s['unit'] for s in result['spans']},
                         {'명리학탐구(고급1) 게시판 글모음#0018', '일주론 글모음#0002'})
        self.assertIsNone(result['independent_support_count'])
        self.assertIs(result['inference_enabled'], False)
        result['item']['review']['conditions'] = 'MUTATED'
        self.assertNotEqual(subject.retrieve(group['member_item_ids'][0])['item']['review']['conditions'], 'MUTATED')
        with self.assertRaisesRegex(ValueError, 'Unknown reviewed item'):
            subject.retrieve('not-an-item')

    def test_partial_reuse_retrieval_preserves_original_comparison_context(self):
        item = next(i for i in self.review['items'] if i['pointer'] == ['distilled', '주의', 3])
        result = subject.retrieve(item['id'])
        self.assertEqual([i['id'] for i in result['prior_review_items']], ['IN06'])
        self.assertEqual(result['prior_review_items'][0]['pointer'], ['관점차이', 0])
        self.assertEqual(len(result['prior_review_items'][0]['draft_value']['견해']), 2)
        self.assertEqual({s['unit'] for s in result['spans']},
                         {'명리학탐구(고급1) 게시판 글모음#0018', '일주론 글모음#0002'})
        self.assertIs(result['delivery_policy']['added_to_app_policy'], False)
        self.assertTrue(result['unreviewed_scope'])

    def test_editorial_changes_remain_canonically_pinned(self):
        review = self.altered()
        review['items'][0]['review']['conditions'] += ' Unsanctioned reinterpretation.'
        with self.assertRaisesRegex(ValueError, 'Reviewed payload changed'):
            subject.validate(review)


if __name__ == '__main__':
    unittest.main()
